
name: Deploy Strapi to Azure App Service

on:
  push:
    branches: [master]

concurrency:
  group: appservice-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: backend/yarn.lock

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build Strapi
        run: yarn build

      - name: Prepare production package
        run: |
          rm -rf node_modules
          yarn install --production --frozen-lockfile
          printf "__tests__\ntest\ntests\ncoverage\n*.md\nCHANGELOG*\nexample\nexamples\ndocs\n" > .yarnclean
          yarn autoclean --force || true
          rm -rf .cache .tmp **/*.map **/.vscode **/.github
          zip -r -9 ../strapi-release.zip . \
            -x "*.git*" "node_modules/.cache/**" "**/__tests__/**" "**/tests/**" "**/*.map"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: strapi-release
          path: strapi-release.zip
          retention-days: 7

  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: strapi-release
            path: .

        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v3
          with:
            app-name: "fld-int-backend"
            slot-name: "Production"
            package: strapi-release.zip
            publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A1985CDD098C488DB3E8DD6AD6D10E1B }}