

name: PIpeline backend v2

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: fld-int-backend
  cancel-in-progress: false


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        env:
          NODE_ENV: production
          ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
          API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
          APP_KEYS: ${{ secrets.APP_KEYS }}
          CLOUDINARY_KEY: ${{ secrets.CLOUDINARY_KEY }}
          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
          CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
          DATABASE_CLIENT: ${{ secrets.DATABASE_CLIENT }}
          DATABASE_SSL: ${{ secrets.DATABASE_SSL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TRANSFER_TOKEN_SALT: ${{ secrets.TRANSFER_TOKEN_SALT }}

        run: |
          cd backend
          npm install
          npm run build --if-present --no-lint
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend  

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./backend 
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fld-int-backend'
          slot-name: 'Production'
          package: ./backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_921B2D17A64C419791D5335854864FB8 }}


